Repository gardener/gardener-extension-os-coreos, pull requests merged in 2021-06, with the labels that each got.

#22 Update golang and alpine
  Dockerfile
  go.mod
  go.sum
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#24 Support transmitUnencoded flag
  go.mod
  pkg/coreos/actuator_reconcile.go
  pkg/coreos/actuator_test.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_delete.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_migrate.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_reconcile.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_restore.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/actuator/actuator_util.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/cloudinit/cloudinit.go
  vendor/github.com/gardener/gardener/extensions/pkg/controller/operatingsystemconfig/oscommon/generator/generator.go
  vendor/modules.txt
Labels: area/security, kind/enhancement, merge/squash, needs/ok-to-test, reviewed/lgtm, size/s

#27 Small improvement in Github template generation
  Makefile
Labels: area/os, needs/ok-to-test, needs/review, size/xs
