Repository gardener/gardener-extension-os-coreos, pull requests merged in 2022-05, with the labels that each got.

#42 update alpine base image to 3.15.4
  Dockerfile
Labels: kind/technical-debt, needs/ok-to-test, reviewed/lgtm, size/xs, area/os

#43 update build container to golang 1.17.9
  Dockerfile
Labels: kind/technical-debt, needs/ok-to-test, needs/review, size/xs, area/os

#40 CgroupsV2 based Flatcar version support
  pkg/coreos/actuator_reconcile.go
  pkg/coreos/actuator_test.go
  pkg/coreos/templates/configure-cgroupsv2.sh.tpl
  pkg/coreos/templates/containerd/run-command.sh.tpl
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/m, area/os
