Repository gardener/gardener-extension-os-coreos, pull requests merged in 2022-08, with the labels that each got.

#49 assign image responsible
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs, area/os

#50 Bump golang to 1.17.13
  Dockerfile
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, area/os, os/garden-linux

#48 Remove install-requirement and use tools.mk
  .gitignore
  Makefile
  hack/tools/bin/.gitkeep
Labels: kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs, area/os
