Repository gardener/gardener-extension-os-coreos, pull requests merged in 2023-07, with the labels that each got.

#64 Drop support for Shoots with Kubernetes version < 1.22
  charts/gardener-extension-os-coreos/templates/poddisruptionbudget.yaml
  example/controller-registration.yaml
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, merge/squash

#65 Introduce persona-based docs
  .docforge/manifest.yaml
  docs/usage/usage.md
Labels: kind/cleanup, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs

#66 Add dependabot to manage Gardener packages
  .github/dependabot.yaml
  .github/workflows/vendor_gardener.yaml
Labels: kind/technical-debt, needs/ok-to-test, reviewed/lgtm, size/s, area/os, os/suse-chost
