Repository gardener/gardener-extension-os-coreos, pull requests merged in 2024-04, with the labels that each got.

#96 Add codeowners from STACKIT
  CODEOWNERS
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/ok-to-test, reviewed/lgtm, size/xs, area/os

#95 Make repo compliant
  .reuse/dep5
  CONTRIBUTING.md
  LICENSE
  LICENSES/Apache-2.0.txt
  LICENSES/BSD-2-Clause.txt
  LICENSES/BSD-3-Clause.txt
  LICENSES/CC-BY-4.0.txt
  LICENSES/ISC.txt
  LICENSES/MIT.txt
  LICENSES/MPL-2.0.txt
  Makefile
  NOTICE.md
  README.md
  charts/gardener-extension-os-coreos/doc.go
  cmd/gardener-extension-os-coreos/app/app.go
  cmd/gardener-extension-os-coreos/main.go
  example/controller-registration.yaml
  hack/tools.go
  hack/update-github-templates.sh
  pkg/controller/operatingsystemconfig/actuator.go
  pkg/controller/operatingsystemconfig/actuator_test.go
  pkg/controller/operatingsystemconfig/add.go
  pkg/controller/operatingsystemconfig/coreos/coreos_suite_test.go
  pkg/controller/operatingsystemconfig/coreos/types.go
  pkg/controller/operatingsystemconfig/coreos_reconcile.go
  pkg/controller/operatingsystemconfig/coreos_reconcile_test.go
  pkg/controller/operatingsystemconfig/operatingsystemconfig_suite_test.go
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xl, area/compliance, area/ipcei

#98 Update slack-cfg used to publish release-notes
  .ci/pipeline_definitions
Labels: area/open-source, kind/cleanup, needs/ok-to-test, needs/review, size/xs

#103 [release-v1.21] Fix filepath collection for files with `ImageRef`
  pkg/controller/operatingsystemconfig/coreos_reconcile.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/os

#102 [release-v1.20] Fix filepath collection for files with `ImageRef`
  pkg/controller/operatingsystemconfig/coreos_reconcile.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/os

#101 [release-v1.19] Fix filepath collection for files with `ImageRef`
  pkg/controller/operatingsystemconfig/coreos_reconcile.go
Labels: kind/bug, needs/ok-to-test, reviewed/lgtm, size/xs, area/os
