Repository gardener/gardener-extension-os-coreos, pull requests merged in 2025-08, with the labels that each got.

#209 REUSE: Convert DEP5 to REUSE.toml
  .reuse/dep5
  REUSE.toml
Labels: area/open-source, kind/enhancement, needs/review, needs/second-opinion, size/xl

#217 Fix head-update gh action
  .github/workflows/head-update.yaml
Labels: kind/regression, needs/review, size/xs, area/os

#221 Remove timebertt from `CODEOWNERS`
  CODEOWNERS
Labels: kind/cleanup, needs/review, size/xs, area/os
