Repository gardener/gardener-extension-os-coreos, pull requests merged in 2025-04, with the labels that each got.

#176 Address TODO for legacy NetworkPolicy labels
  charts/gardener-extension-os-coreos/templates/service.yaml
  example/controller-registration.yaml
Labels: kind/cleanup, needs/ok-to-test, reviewed/lgtm, size/xs, area/os

#177 Switch Slack references to Gardener workspace
  README.md
Labels: area/open-source, kind/enhancement, needs/ok-to-test, reviewed/lgtm, size/xs

#181 Allow `patch` of the `gardener-extension-heartbeat` lease
  charts/gardener-extension-os-coreos/templates/rbac.yaml
  example/controller-registration.yaml
Labels: kind/regression, needs/ok-to-test, needs/review, size/xs, area/os

#182 Add vincinator as responsible
  .ci/pipeline_definitions
Labels: needs/ok-to-test, reviewed/lgtm, size/xs, area/os
